// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Adapter from "../Adapter.res.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";

let baseUrl = {
  contents: $$Deno.Env.getWithDefault("GRAFANA_URL", "http://localhost:3000")
};

let apiKey = {
  contents: $$Deno.Env.getWithDefault("GRAFANA_API_KEY", "")
};

let connected = {
  contents: false
};

function getHeaders() {
  let headers = {};
  let key = apiKey.contents;
  if (key !== "") {
    headers["Authorization"] = `Bearer ` + key;
  }
  headers["Content-Type"] = "application/json";
  return headers;
}

async function connect() {
  let url = baseUrl.contents + "/api/health";
  let e = await $$Deno.Fetch.get(url, getHeaders());
  if (e.TAG === "Ok") {
    connected.contents = true;
    return;
  } else {
    return Stdlib_Exn.raiseError(`Failed to connect to Grafana: ` + e._0);
  }
}

async function disconnect() {
  connected.contents = false;
}

async function isConnected() {
  return connected.contents;
}

async function searchDashboardsHandler(args) {
  let match = args["query"];
  let query = typeof match === "string" ? match : "";
  let match$1 = args["tag"];
  let tag = typeof match$1 === "string" ? match$1 : undefined;
  let url = tag !== undefined ? baseUrl.contents + `/api/search?query=` + query + `&tag=` + tag : baseUrl.contents + `/api/search?query=` + query;
  let data = await $$Deno.Fetch.get(url, getHeaders());
  if (data.TAG === "Ok") {
    return data._0;
  } else {
    return Stdlib_Exn.raiseError(data._0);
  }
}

async function getDashboardHandler(args) {
  let match = args["uid"];
  let uid = typeof match === "string" ? match : Stdlib_Exn.raiseError("uid parameter is required");
  let url = baseUrl.contents + `/api/dashboards/uid/` + uid;
  let data = await $$Deno.Fetch.get(url, getHeaders());
  if (data.TAG === "Ok") {
    return data._0;
  } else {
    return Stdlib_Exn.raiseError(data._0);
  }
}

async function listDataSourcesHandler(_args) {
  let url = baseUrl.contents + `/api/datasources`;
  let data = await $$Deno.Fetch.get(url, getHeaders());
  if (data.TAG === "Ok") {
    return data._0;
  } else {
    return Stdlib_Exn.raiseError(data._0);
  }
}

async function getDataSourceHandler(args) {
  let match = args["name"];
  let name = typeof match === "string" ? match : Stdlib_Exn.raiseError("name parameter is required");
  let url = baseUrl.contents + `/api/datasources/name/` + name;
  let data = await $$Deno.Fetch.get(url, getHeaders());
  if (data.TAG === "Ok") {
    return data._0;
  } else {
    return Stdlib_Exn.raiseError(data._0);
  }
}

async function listFoldersHandler(_args) {
  let url = baseUrl.contents + `/api/folders`;
  let data = await $$Deno.Fetch.get(url, getHeaders());
  if (data.TAG === "Ok") {
    return data._0;
  } else {
    return Stdlib_Exn.raiseError(data._0);
  }
}

async function getAlertRulesHandler(_args) {
  let url = baseUrl.contents + `/api/v1/provisioning/alert-rules`;
  let data = await $$Deno.Fetch.get(url, getHeaders());
  if (data.TAG === "Ok") {
    return data._0;
  } else {
    return Stdlib_Exn.raiseError(data._0);
  }
}

async function getAnnotationsHandler(args) {
  let match = args["from"];
  let from = typeof match === "string" ? match : "";
  let match$1 = args["to"];
  let to_ = typeof match$1 === "string" ? match$1 : "";
  let match$2 = args["dashboardId"];
  let dashboardId = typeof match$2 === "number" ? match$2.toString() : undefined;
  let params = [];
  if (from !== "") {
    params.push(`from=` + from);
  }
  if (to_ !== "") {
    params.push(`to=` + to_);
  }
  if (dashboardId !== undefined) {
    params.push(`dashboardId=` + dashboardId);
  }
  let queryString = params.join("&");
  let url = queryString !== "" ? baseUrl.contents + `/api/annotations?` + queryString : baseUrl.contents + `/api/annotations`;
  let data = await $$Deno.Fetch.get(url, getHeaders());
  if (data.TAG === "Ok") {
    return data._0;
  } else {
    return Stdlib_Exn.raiseError(data._0);
  }
}

async function getOrgHandler(_args) {
  let url = baseUrl.contents + `/api/org`;
  let data = await $$Deno.Fetch.get(url, getHeaders());
  if (data.TAG === "Ok") {
    return data._0;
  } else {
    return Stdlib_Exn.raiseError(data._0);
  }
}

let tools = Object.fromEntries([
  [
    "grafana_search_dashboards",
    {
      description: "Search for dashboards by name or tag",
      params: Object.fromEntries([
        [
          "query",
          Adapter.stringParam("Search query")
        ],
        [
          "tag",
          Adapter.stringParam("Filter by tag")
        ]
      ]),
      handler: searchDashboardsHandler
    }
  ],
  [
    "grafana_get_dashboard",
    {
      description: "Get a dashboard by UID",
      params: Object.fromEntries([[
          "uid",
          Adapter.stringParam("Dashboard UID")
        ]]),
      handler: getDashboardHandler
    }
  ],
  [
    "grafana_list_datasources",
    {
      description: "List all configured data sources",
      params: {},
      handler: listDataSourcesHandler
    }
  ],
  [
    "grafana_get_datasource",
    {
      description: "Get data source details by name",
      params: Object.fromEntries([[
          "name",
          Adapter.stringParam("Data source name")
        ]]),
      handler: getDataSourceHandler
    }
  ],
  [
    "grafana_list_folders",
    {
      description: "List all dashboard folders",
      params: {},
      handler: listFoldersHandler
    }
  ],
  [
    "grafana_get_alert_rules",
    {
      description: "Get all alert rules",
      params: {},
      handler: getAlertRulesHandler
    }
  ],
  [
    "grafana_get_annotations",
    {
      description: "Get annotations within a time range",
      params: Object.fromEntries([
        [
          "from",
          Adapter.stringParam("Start time (Unix ms or ISO)")
        ],
        [
          "to",
          Adapter.stringParam("End time (Unix ms or ISO)")
        ],
        [
          "dashboardId",
          Adapter.numberParam("Filter by dashboard ID")
        ]
      ]),
      handler: getAnnotationsHandler
    }
  ],
  [
    "grafana_get_org",
    {
      description: "Get current organization info",
      params: {},
      handler: getOrgHandler
    }
  ]
]);

let name = "grafana";

let description = "Grafana dashboard and visualization adapter";

export {
  baseUrl,
  apiKey,
  connected,
  name,
  description,
  getHeaders,
  connect,
  disconnect,
  isConnected,
  searchDashboardsHandler,
  getDashboardHandler,
  listDataSourcesHandler,
  getDataSourceHandler,
  listFoldersHandler,
  getAlertRulesHandler,
  getAnnotationsHandler,
  getOrgHandler,
  tools,
}
/* baseUrl Not a pure module */
