// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";
import * as Adapter from "../Adapter.res.js";
import * as Stdlib_Exn from "@rescript/runtime/lib/es6/Stdlib_Exn.js";

let jaegerUrl = {
  contents: $$Deno.Env.getWithDefault("JAEGER_URL", "http://localhost:16686")
};

let connected = {
  contents: false
};

async function connect() {
  let e = await $$Deno.Fetch.get(jaegerUrl.contents + `/api/services`, undefined);
  if (e.TAG === "Ok") {
    connected.contents = true;
    return;
  } else {
    return Stdlib_Exn.raiseError(`Failed to connect to Jaeger: ` + e._0);
  }
}

async function disconnect() {
  connected.contents = false;
}

async function isConnected() {
  return connected.contents;
}

async function servicesHandler(_args) {
  let result = await $$Deno.Fetch.get(jaegerUrl.contents + `/api/services`, undefined);
  if (result.TAG === "Ok") {
    return result._0;
  } else {
    return Stdlib_Exn.raiseError(result._0);
  }
}

async function tracesHandler(args) {
  let match = args["service"];
  let service = typeof match === "string" ? match : Stdlib_Exn.raiseError("service parameter is required");
  let match$1 = args["operation"];
  let operation = typeof match$1 === "string" ? match$1 : undefined;
  let match$2 = args["limit"];
  let limit = typeof match$2 === "number" ? match$2 | 0 : 20;
  let match$3 = args["lookback"];
  let lookback = typeof match$3 === "string" ? match$3 : "1h";
  let params = [
    `service=` + service,
    `limit=` + limit.toString(),
    `lookback=` + lookback
  ];
  if (operation !== undefined) {
    params.push(`operation=` + operation);
  }
  let url = jaegerUrl.contents + `/api/traces?` + params.join("&");
  let result = await $$Deno.Fetch.get(url, undefined);
  if (result.TAG === "Ok") {
    return result._0;
  } else {
    return Stdlib_Exn.raiseError(result._0);
  }
}

async function traceHandler(args) {
  let match = args["traceId"];
  let traceId = typeof match === "string" ? match : Stdlib_Exn.raiseError("traceId parameter is required");
  let result = await $$Deno.Fetch.get(jaegerUrl.contents + `/api/traces/` + traceId, undefined);
  if (result.TAG === "Ok") {
    return result._0;
  } else {
    return Stdlib_Exn.raiseError(result._0);
  }
}

async function operationsHandler(args) {
  let match = args["service"];
  let service = typeof match === "string" ? match : Stdlib_Exn.raiseError("service parameter is required");
  let result = await $$Deno.Fetch.get(jaegerUrl.contents + `/api/services/` + service + `/operations`, undefined);
  if (result.TAG === "Ok") {
    return result._0;
  } else {
    return Stdlib_Exn.raiseError(result._0);
  }
}

async function dependenciesHandler(args) {
  let match = args["endTs"];
  let endTs = typeof match === "number" ? match | 0 : 0;
  let match$1 = args["lookback"];
  let lookback = typeof match$1 === "number" ? match$1 | 0 : 3600000;
  let url = endTs > 0 ? jaegerUrl.contents + `/api/dependencies?endTs=` + endTs.toString() + `&lookback=` + lookback.toString() : jaegerUrl.contents + `/api/dependencies?lookback=` + lookback.toString();
  let result = await $$Deno.Fetch.get(url, undefined);
  if (result.TAG === "Ok") {
    return result._0;
  } else {
    return Stdlib_Exn.raiseError(result._0);
  }
}

let tools = Object.fromEntries([
  [
    "jaeger_services",
    {
      description: "List all services in Jaeger",
      params: {},
      handler: servicesHandler
    }
  ],
  [
    "jaeger_traces",
    {
      description: "Get traces for a service",
      params: Object.fromEntries([
        [
          "service",
          Adapter.stringParam("Service name")
        ],
        [
          "operation",
          Adapter.stringParam("Operation name (optional)")
        ],
        [
          "limit",
          Adapter.numberParam("Max traces to return (default: 20)")
        ],
        [
          "lookback",
          Adapter.stringParam("Time range (e.g., '1h', '30m')")
        ]
      ]),
      handler: tracesHandler
    }
  ],
  [
    "jaeger_trace",
    {
      description: "Get a specific trace by ID",
      params: Object.fromEntries([[
          "traceId",
          Adapter.stringParam("Trace ID")
        ]]),
      handler: traceHandler
    }
  ],
  [
    "jaeger_operations",
    {
      description: "Get operations for a service",
      params: Object.fromEntries([[
          "service",
          Adapter.stringParam("Service name")
        ]]),
      handler: operationsHandler
    }
  ],
  [
    "jaeger_dependencies",
    {
      description: "Get service dependency graph",
      params: Object.fromEntries([
        [
          "endTs",
          Adapter.numberParam("End timestamp (ms since epoch)")
        ],
        [
          "lookback",
          Adapter.numberParam("Lookback window in ms")
        ]
      ]),
      handler: dependenciesHandler
    }
  ]
]);

let name = "jaeger";

let description = "Jaeger distributed tracing";

export {
  jaegerUrl,
  connected,
  name,
  description,
  connect,
  disconnect,
  isConnected,
  servicesHandler,
  tracesHandler,
  traceHandler,
  operationsHandler,
  dependenciesHandler,
  tools,
}
/* jaegerUrl Not a pure module */
